name: Deploy to VPS

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps & build (frontend)
        working-directory: frontend
        run: |
          npm ci || npm install
          npm run build

      - name: Pack build
        run: tar -czf site.tgz -C frontend build

      - name: Upload build to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "site.tgz"
          target: "/tmp"

      - name: Release switch on VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -euo pipefail
            REL="/var/www/dataads/releases/${GITHUB_SHA::7}"
            mkdir -p "$REL"
            tar -xzf /tmp/site.tgz -C "$REL" --strip-components=1
            ln -sfn "$REL" /var/www/dataads/current
            systemctl reload nginx
            echo "==> Deployed $REL"

