name: Deploy to VPS

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Build frontend
        working-directory: frontend
        run: |
          npm ci
          npm run build

      - name: Pack build
        run: tar -czf site.tgz -C frontend build

      - name: Upload to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "site.tgz"
          target: "/tmp/site.tgz"

      - name: Release switch on VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e
            mkdir -p /var/www/dataads/releases
            REL="/var/www/dataads/releases/$(date +%s)"
            mkdir -p "$REL"
            tar -xzf /tmp/site.tgz -C "$REL" --strip-components=1
            ln -sfn "$REL" /var/www/dataads/current
            nginx -t && systemctl reload nginx
            echo "✅ Deployed to $REL"

